### ISSUE TITLE
Add a cmake rule to detect that jinja2 is missing

### ISSUE THREAD

**Issue by wkirschenmann** [aneoconsulting/PENE#27]

**Comment by wkirschenmann** [comment]
see [https://stackoverflow.com/a/62558155](https://stackoverflow.com/a/62558155)
However, it would be best to create a new command to find the python modules that we could reuse in differrent places (ex: #33).

**Comment by melflitty** [comment]
Fixed by https://github.com/aneoconsulting/PENE/pull/36
